services:
  db:
    image: "postgres:17"
    container_name: "pokebot-db"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 123
    ports:
      - "5555:5432"
    volumes:
      - "./data:/data"
